### ISSUE TITLE
The FLOPs in the paper is wrong

### ISSUE THREAD

**Issue by leexinhao** [TalalWasim/Vita-CLIP#6]
![image](https://github.com/TalalWasim/Vita-CLIP/assets/48858574/8a3fdfe1-8c7b-47ac-8d6e-3d99f2a32666)
There are two mistakes in Table 1, one is that the FLOPs of EVL  reported are 3 views instead of a single view. Another mistake is that FLOPs of Vita-CLIP-B is too low, even the original CLIP ViT-B has around 140G FLOPs for a single frame input.

**Comment by TalalWasim** [comment]
Thank you for your interest in our work and raising the question regarding the reported FLOPs in our research paper. We would like to clarify that the FLOPs we reported correspond to the inference phase, which has lower computational requirements compared to training. In our method, we pre-compute the text branch during inference, reducing the FLOPs associated with the text branch. Thus, the reported FLOPs only consider the vision branch and assume pre-computed text features, resulting in a lower count. It's worth noting that the XCLIP method utilizes a cross-attention mechanism between the image and text branches during inference. This explicit dependency between the two branches requires joint computations, leading to increased FLOPs. Unlike the XCLIP method, our approach and the original CLIP do not have a text-image dependency, enabling us to pre-compute text features and reduce FLOPs during inference. We appreciate your attention to detail, and we believe these optimizations accurately reflect the computational efficiency of our method. If you have any further questions, please let us know.

**Comment by leexinhao** [comment]
> Thank you for your interest in our work and raising the question regarding the reported FLOPs in our research paper. We would like to clarify that the FLOPs we reported correspond to the inference phase, which has lower computational requirements compared to training. In our method, we pre-compute the text branch during inference, reducing the FLOPs associated with the text branch. Thus, the reported FLOPs only consider the vision branch and assume pre-computed text features, resulting in a lower count. It's worth noting that the XCLIP method utilizes a cross-attention mechanism between the image and text branches during inference. This explicit dependency between the two branches requires joint computations, leading to increased FLOPs. Unlike the XCLIP method, our approach and the original CLIP do not have a text-image dependency, enabling us to pre-compute text features and reduce FLOPs during inference. We appreciate your attention to detail, and we believe these optimizations accurately reflect the computational efficiency of our method. If you have any further questions, please let us know.

I understand that only visual encoders are considered. For a 224 x 224 image, the FLOPs of CLIP-B/16 is 17.5G, and for a 8-frame input, the FLOPs is 17.5x8=140G, **so why your FLOPs is 97G**?

Finally, the FLOPs of EVL for a single view is 454/3=151G.
